### ISSUE TITLE
Different Methods on Datasets

### ISSUE THREAD

**Issue by zhangda1018** [icantnamemyself/FormerTime#1]
Hi，a CLEAR and NICE work!
I notice in table3 "different classification performance of compared methods in ten datasets", can you provide codes of other methods?
I wonder how you use some methods like Informer, GTN for classification.
Thanks!

**Comment by icantnamemyself** [comment]
Hi there!

Thanks for your attention to our work. As for your questions, actually we explained them in Section 4.1.3. In detail, most baseline models are implemented using the implementation of [*tsai*](https://timeseriesai.github.io/tsai/). As for GTN, we use the [source code](https://github.com/ZZUFaceBookDL/GTN  ) provided by the corresponding authors. For Informer, we simply replace the decoder in Informer with a linear classifier layer(nn.Linear) based on its open [source code](https://github.com/zhouhaoyi/Informer2020).

Hope the response be helpful to you!

**Comment by zhangda1018** [comment]
Thanks a lot!
